### ISSUE TITLE
Add a github star⭐

### ISSUE THREAD

**Issue by Savio629** [vinyashegde/shorto_url_shorter#19]
As this is a open source extension, I would like to add a github star in the extension.
So if any one uses it and if they like it, they can give a star to the repository or contribute to the repository.

**Comment by vinyashegde** [comment]
> As this is a open source extension, I would like to add a github star in the extension. So if any one uses it and if they like it, they can give a star to the repository or contribute to the repository.

you have been assigned lets see your creativity!

**Comment by Savio629** [comment]
Check this out
![star (2)](https://user-images.githubusercontent.com/91362589/197698662-e6dc709e-9222-4f3f-a10c-dce00279719f.png)
Is it alright ?

**Comment by vinyashegde** [comment]
Yes go ahead 🙂

**Comment by Savio629** [comment]
There was some issue with the Github star right? @vinyashegde Can you explain the issue...

**Comment by vinyashegde** [comment]
yes the star is not visible!Something must be wrong with library
