### ISSUE TITLE
Button to create a QR code for the currently selected tab

### ISSUE THREAD

**Issue by AsciiJakob** [vinyashegde/shorto_url_shorter#20]
It would be pretty convenient. You click a button, and it generates a qr code for the URL of whatever tab you have selected at the moment.
I wouldn't mind implementing it if you assign the issue to me

**Comment by vinyashegde** [comment]
> It would be pretty convenient. You click a button, and it generates a qr code for the URL of whatever tab you have selected at the moment. I wouldn't mind implementing it if you assign the issue to me

yeah sure go ahead sounds really interesting!
