### ISSUE TITLE
 Improve UI of the extension

### ISSUE THREAD

**Issue by vinyashegde** [vinyashegde/shorto_url_shorter#34]
Submit your design for the extension and then we will choose the design suitable for our project. The design should be minimalist and easy to use. Also changes may require depending on how the design looks

**Comment by niranjan-kurhade** [comment]
![Screenshot 2023-02-25 172626](https://user-images.githubusercontent.com/97905637/221355559-98562079-266b-4de4-b488-b76e80f1fcd3.png)
![Screenshot 2023-02-25 172647](https://user-images.githubusercontent.com/97905637/221355561-b4c0f4c6-2af7-49d9-8e70-6ad6368607d3.png)
Here are the Screenshots of the UI implementation of 2 pages
